version: '3.8'

services:
  php:
    build: .
    container_name: php_server
    volumes:
      - .:/var/www/html
    ports:
      - "81:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
